// action types
export const actionTypes = {
  UPDATE_FIRSTNAME: 'UPDATE_FIRSTNAME',
  UPDATE_LASTNAME: 'UPDATE_LASTNAME',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
}
