// action types
export const actionTypes = {
  UPDATE_FIRSTNAME: 'UPDATE_FIRSTNAME',
  UPDATE_LASTNAME: 'UPDATE_LASTNAME',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_HOMENAME: 'UPDATE_HOMENAME',
  UPDATE_STREET: 'UPDATE_STREET',
  UPDATE_ZIPCODE: 'UPDATE_ZIPCODE',
  UPDATE_CODE: 'UPDATE_CODE',
  ADD_THERMOSTAT: 'ADD_THERMOSTAT',
}
